set(CMAKE_SYSTEM_NAME Windows)

file(TO_CMAKE_PATH "$ENV{MINGW_GCC_PATH}" MINGW_GCC_PATH)

# Compilers to use for C, C++
set(CMAKE_C_COMPILER "${MINGW_GCC_PATH}/bin/gcc.exe")
set(CMAKE_CXX_COMPILER "${MINGW_GCC_PATH}/bin/g++.exe")

# modify default behavior of FIND_XXX() commands
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
